# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches:
      - main
      - develop

jobs:
  build-deploy-main:
    if: github.ref == 'refs/heads/main'
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4

      - uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Copy Repository to remote server
        run: |
          scp -o StrictHostKeyChecking=no -r * ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }}:/home/longplan/backend/main/

      - name: Deploy Docker image on remote server
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }} << EOF
            docker rm \$(docker ps -aqf "name=${{ env.APP_NAME }}") -f || true
            docker rmi \$(docker images -aqf "reference=${{ env.APP_NAME }}") || true
            docker build --platform linux/amd64 -t ${{ env.APP_NAME }} /home/longplan/backend/main/
            docker run -d -p 5000:5000 -v /home/longplan/backend/main/config:/config -e mode='prod' --restart unless-stopped --name ${{ env.APP_NAME }} ${{ env.APP_NAME }}
            find /home/longplan/backend/main/ -mindepth 1 ! -path "/home/longplan/backend/main/config" ! -path "/home/longplan/backend/main/config/config.prod.yaml" -delete
            docker system prune -a -f
          EOF

    env:
      APP_NAME: prod-longplan-api

  build-deploy-develop:
    if: github.ref == 'refs/heads/develop'
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4

      - uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Copy Repository to remote server
        run: |
          scp -o StrictHostKeyChecking=no -r * ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }}:/home/longplan/backend/develop/

      - name: Deploy Docker image on remote server
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }} << EOF
            
            docker rm \$(docker ps -aqf "name=${{ env.APP_NAME }}") -f || true
            docker rmi \$(docker images -aqf "reference=${{ env.APP_NAME }}") || true
            docker build --platform linux/amd64 -t ${{ env.APP_NAME }} /home/longplan/backend/develop/
            docker run -d -p 8000:8000 -v /home/longplan/backend/develop/config:/config -e mode='dev' --restart unless-stopped --name ${{ env.APP_NAME }} ${{ env.APP_NAME }}
            find /home/longplan/backend/develop/ -mindepth 1 ! -path "/home/longplan/backend/develop/config" ! -path "/home/longplan/backend/develop/config/config.dev.yaml" -delete
            docker system prune -a -f
          EOF

    env:
      APP_NAME: dev-longplan-api
